### ISSUE TITLE
Domain

### ISSUE THREAD

**Issue by miladrahimi** [alimardani94/alimardani94.github.io#1]
Domain-e alimardani.me ro kharidi?

**Comment by alimardani94** [comment]
اره به زودی شاهد این دامین خواهی بود

**Comment by alimardani94** [comment]
تو از کجا فهمیدی

**Comment by alimardani94** [comment]
نمیدونم چه جوری کلودفلر رو روی گیتهاب ست کنم ؟ بعدا یه بار باید ازت بپرسم
